start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

gaps.inner.horizontal = 4
gaps.inner.vertical =   4
gaps.outer.left =       0
gaps.outer.bottom =     0
gaps.outer.top =        0
gaps.outer.right =      0

non-empty-workspaces-root-containers-layout-on-startup = 'tiles'

[workspace-to-monitor-force-assignment]
s = 'secondary'

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through up'
alt-shift-l = 'move-through right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace s'
alt-tab = 'workspace-back-and-forth'

cmd-ctrl-a = 'mode aerospace'

[mode.aerospace.binding]
1 = ['move-node-to-workspace 1', 'mode main']
2 = ['move-node-to-workspace 2', 'mode main']
3 = ['move-node-to-workspace 3', 'mode main']
4 = ['move-node-to-workspace 4', 'mode main']
5 = ['move-node-to-workspace 5', 'mode main']
6 = ['move-node-to-workspace 6', 'mode main']
7 = ['move-node-to-workspace 7', 'mode main']
8 = ['move-node-to-workspace 8', 'mode main']
9 = ['move-node-to-workspace 9', 'mode main']
0 = ['move-node-to-workspace s', 'mode main']

h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

f = ['layout floating tiling', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
enter = ['fullscreen', 'mode main']

esc = 'mode main'
